import{cp,mkdir,readFile,rm,writeFile}from"node:fs/promises";
import{createHash}from"node:crypto";
import{resolve}from"node:path";

const root=resolve(import.meta.dirname,"..");
const dist=resolve(root,"dist");
await rm(dist,{recursive:true,force:true});
await mkdir(resolve(dist,"data"),{recursive:true});
for(const file of["index.html","styles.css","app.js"])await cp(resolve(root,"src",file),resolve(dist,file));
await cp(resolve(root,"src","control"),resolve(dist,"control"),{recursive:true});
await cp(resolve(root,"content","game-runtime-media.json"),resolve(dist,"data","game-runtime-media.json"));
await cp(resolve(root,"content","asset-resolution.json"),resolve(dist,"data","asset-resolution.json"));
await cp(resolve(root,"content","control-runtime.json"),resolve(dist,"data","control-runtime.json"));
const csv=await readFile(resolve(root,"content","website-visual-assets.csv"),"utf8");
const lines=csv.trim().split(/\r?\n/);
const headers=lines.shift().split(",");
const parse=line=>{const cells=[];let value="";let quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){cells.push(value);value=""}else value+=c}cells.push(value);return Object.fromEntries(headers.map((h,i)=>[h,cells[i]??""]))};
const assets=lines.filter(Boolean).map(parse);
await writeFile(resolve(dist,"data","website-visual-assets.json"),JSON.stringify({schema:"biella.website.visual-assets/v1",assets},null,2)+"\n");
const sourceCommit=process.env.BIELLA_SOURCE_COMMIT||"LOCAL_UNPUBLISHED";
const sourceTree=process.env.BIELLA_SOURCE_TREE||"UNKNOWN";
const environment=process.env.BIELLA_DEPLOY_ENV||"LOCAL";
const deploymentStatus=process.env.BIELLA_DEPLOYMENT_STATUS||"NOT_REMOTELY_DEPLOYED";
const html=await readFile(resolve(dist,"index.html"));
const artifactSha256=createHash("sha256").update(html).digest("hex");
const deployment={schema:"biella.website.deployment/v1",source_commit:sourceCommit,source_tree:sourceTree,source_branch:process.env.BIELLA_SOURCE_BRANCH||"website",environment,deployment_status:deploymentStatus,entrypoint_sha256:artifactSha256,generated_at:new Date().toISOString()};
await writeFile(resolve(dist,"deployment.json"),JSON.stringify(deployment,null,2)+"\n");
await writeFile(resolve(dist,"404.html"),html);
console.log(JSON.stringify({dist,...deployment},null,2));
